version: '3'
services:
  mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    command: mongod --bind_ip_all

  app:
    depends_on:
      - "mongodb"
    build: .
    command: yarn dev
    ports:
      - "8080:8080"
    volumes:
      - .:/aircnc_app

volumes: 
  mongodb: